name = "chaman-properties-website"
compatibility_date = "2026-05-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[vars]
NEXT_PUBLIC_SITE_URL = "https://chamanproperties.com"
NEXT_PUBLIC_SANITY_PROJECT_ID = "eeuefmhu"
NEXT_PUBLIC_SANITY_DATASET = "production"
NEXT_PUBLIC_SANITY_API_VERSION = "2026-05-17"
NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION = ""
NEXT_PUBLIC_BING_SITE_VERIFICATION = ""
